# ~/.config/yazi/yazi.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 2, 4 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "size"
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]

[opener]
edit = [
	{ run = 'zed %s', desc = "Zed", for = "macos", block = false },
	{ run = 'zeditor %s', desc = "Zed", for = "linux", block = false },
	{ run = '${EDITOR:-vi} %s', desc = "$EDITOR", for = "unix", block = true },
]
open = [
	{ run = 'xdg-open %s1',    desc = "Open", for = "linux" },
	{ run = 'open %s',         desc = "Open", for = "macos" },
]
reveal = [
	{ run = 'xdg-open %d1',         desc = "Reveal", for = "linux" },
	{ run = 'open -R %s1',          desc = "Reveal", for = "macos" },
]
extract = [
	{ run = 'ya pub extract --list %s', desc = "Extract here" },
]
play = [
	{ run = 'mpv %s', orphan = true, desc = "Play" },
]

[open]
rules = [
	{ url = "*/", use = [ "edit", "open", "reveal" ] },
	{ mime = "text/*", use = [ "edit", "reveal" ] },
	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	{ mime = "application/pdf", use = [ "open", "reveal" ] },
	{ url = "*", use = [ "open", "reveal" ] },
]

[preview]
tab_size        = 2
max_width       = 1200
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75

[plugin]
fetchers = [
	{ id = "mime", url = "*/", run = "mime.dir", prio = "high" },
]
previewers = [
	{ url = "*/", run = "folder" },
	{ mime = "text/*", run = "code" },
	{ mime = "application/json", run = "json" },
	{ mime = "image/*", run = "image" },
	{ mime = "video/*", run = "video" },
	{ mime = "application/pdf", run = "pdf" },
]
